name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4 # v4はデフォルトでキャッシュ（モジュール・バイナリ共に）
        with:
          go-version: "1.19"

      - name: Build binary file
        run: go build main.go

      # TODO:scp/ssh共に冗長なので別ファイルに切り出して共通化 & 並列実行したい
      - name: Copy execution files to first server via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.EC2_FIRST_IP_ADDRESS }}
          username: ${{ vars.EC2_USER_NAME }}
          key: ${{ secrets.EC2_FIRST_PRIVATE_KEY }}
          port: 22
          source: "main,migrations/*"
          target: /home/${{ vars.EC2_USER_NAME }}

      - name: Copy execution files to second server via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.EC2_SECOND_IP_ADDRESS }}
          username: ${{ vars.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SECOND_PRIVATE_KEY }}
          port: 22
          source: "main,migrations/*"
          target: /home/${{ vars.EC2_USER_NAME }}

      - name: Restart web hosting service on first server via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_FIRST_IP_ADDRESS }}
          username: ${{ vars.EC2_USER_NAME }}
          key: ${{ secrets.EC2_FIRST_PRIVATE_KEY }}
          port: 22
          script: sudo systemctl restart portfolio.service

      - name: Restart web hosting service on second server via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_SECOND_IP_ADDRESS }}
          username: ${{ vars.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SECOND_PRIVATE_KEY }}
          port: 22
          script: sudo systemctl restart portfolio.service
